CREATE DATABASE PRODU;
USE produ;

CREATE TABLE produtos(
id INT ALTO_INCLEMENT PRIMARI KEY,
nome VARCHAR(100) NOT NULL,
categoria VARCHAR (100) NOT NULL, 
preco DECIMAL (10,2) NOT NULL,
quantidade INT NOT NULL
);